### ISSUE TITLE
Missing Dependencies : google-cloud-speech

### ISSUE THREAD

**Issue by Yuelioi** [dmcrobin/AudioScript#1]
Hi,something wrong with me:
google-cloud : v0.34

Traceback (most recent call last):
    File "F:/Python/Project/Subtitle/AudioScript-master/AudioScript-master/audioscript.py", line 13, in <module>
    from google.cloud import speech_v1p1beta1 as speech
ImportError: cannot import name 'speech_v1p1beta1' from 'google.cloud' (unknown location)

**Comment by prkindia** [comment]
> Hi,something wrong with me:
> google-cloud : v0.34
> 
> Traceback (most recent call last):
>     File "F:/Python/Project/Subtitle/AudioScript-master/AudioScript-master/audioscript.py", line 13, in <module>
>     from google.cloud import speech_v1p1beta1 as speech
> ImportError: cannot import name 'speech_v1p1beta1' from 'google.cloud' (unknown location)

In order to use the Cloud Speech API, you need to install the module by using `pip install google-cloud-speech`. 

**_Thanks for the issue, updating the modules.txt file._**

**This project does not contain the secret.json file which you need to download from your cloud console.**
